import { Task, TaskCategory, TaskDifficulty, TaskFrequency, TaskPriority, TaskStatus } from "@/types/task";
import { UserGroup } from "@/types/user";

export const sampleTasks: Task[] = [
  {
    id: 1,
    title: "Complete Math Homework",
    category: TaskCategory.Academic,
    frequency: TaskFrequency.Weekly,
    difficulty: TaskDifficulty.Medium,
    status: TaskStatus.Todo,
    priority: TaskPriority.High,
    dueDate: new Date("2023-06-15"),
    createdAt: new Date("2023-06-10"),
    updatedAt: new Date("2023-06-10"),
    description: "Finish algebra exercises from chapter 5",
    assignedTo: ["mathwhiz"],
    tags: [{ id: "1", name: "Math", color: "#FF5733" }],
  },
  {
    id: 2,
    title: "Clean Room",
    category: TaskCategory.Household,
    frequency: TaskFrequency.Daily,
    difficulty: TaskDifficulty.Easy,
    status: TaskStatus.InProgress,
    priority: TaskPriority.Medium,
    dueDate: new Date("2023-06-11"),
    createdAt: new Date("2023-06-09"),
    updatedAt: new Date("2023-06-10"),
    note: "Don't forget to organize desk drawers",
    assignedTo: ["tidykid", "otherkid"],
  },
  {
    id: 3,
    title: "Help Neighbor with Gardening",
    category: TaskCategory.Helpful,
    frequency: TaskFrequency.Monthly,
    difficulty: TaskDifficulty.Medium,
    status: TaskStatus.Todo,
    priority: TaskPriority.Low,
    dueDate: new Date("2023-06-20"),
    createdAt: new Date("2023-06-05"),
    updatedAt: new Date("2023-06-05"),
    description: "Help Mrs. Johnson plant new flowers in her garden",
    assignedTo: [ "helpfulkid"],
    tags: [{ id: "2", name: "Outdoor", color: "#33FF57" }],
    comments: [{
      id: "1",
      content: "Remember to bring gardening gloves!",
      author: { id: 4, email: "parent@example.com", username: "parentuser", group: UserGroup.PARENT },
      createdAt: new Date("2023-06-06"),
    }],
  },
];