/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as testTestRouteImport } from './routes/(test)/test_'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authAuthRouteImport } from './routes/(auth)/_auth'
import { Route as appParentsRouteImport } from './routes/(app)/_parents'
import { Route as appKidsRouteImport } from './routes/(app)/_kids'
import { Route as appExamplesRouteImport } from './routes/(app)/_examples'
import { Route as appAdminRouteImport } from './routes/(app)/_admin'
import { Route as testTestARouteImport } from './routes/(test)/test.a_'
import { Route as authAuthProfileRouteImport } from './routes/(auth)/_auth.profile'
import { Route as appParentsParentsIndexRouteImport } from './routes/(app)/_parents/parents.index'
import { Route as appKidsKidsIndexRouteImport } from './routes/(app)/_kids/kids.index'
import { Route as appAdminAdminIndexRouteImport } from './routes/(app)/_admin/admin.index'
import { Route as testTestASomethingRouteImport } from './routes/(test)/test.a.something'
import { Route as testTestABRouteImport } from './routes/(test)/test.a.b_'
import { Route as appParentsParentsTasksRouteImport } from './routes/(app)/_parents/parents.tasks_'
import { Route as appParentsParentsRoutinesRouteImport } from './routes/(app)/_parents/parents.routines'
import { Route as appParentsParentsRewardsRouteImport } from './routes/(app)/_parents/parents.rewards_'
import { Route as appParentsParentsApprovalsRouteImport } from './routes/(app)/_parents/parents.approvals'
import { Route as appParentsParentsAchievementsRouteImport } from './routes/(app)/_parents/parents.achievements'
import { Route as appKidsKidsPlayRouteImport } from './routes/(app)/_kids/kids.play'
import { Route as appKidsKidsHelpRouteImport } from './routes/(app)/_kids/kids.help'
import { Route as appKidsKidsFitnessRouteImport } from './routes/(app)/_kids/kids.fitness'
import { Route as appKidsKidsEarnRouteImport } from './routes/(app)/_kids/kids.earn'
import { Route as appExamplesDemoTestingRouteImport } from './routes/(app)/_examples/demo.testing'
import { Route as appExamplesDemoDialogsRouteImport } from './routes/(app)/_examples/demo.dialogs'
import { Route as appAdminAdminUsersRouteImport } from './routes/(app)/_admin/admin.users'
import { Route as appAdminAdminAnalyticsRouteImport } from './routes/(app)/_admin/admin.analytics'
import { Route as testTestABCRouteImport } from './routes/(test)/test.a.b.c'
import { Route as appParentsParentsTasksSequenceNumberRouteImport } from './routes/(app)/_parents/parents.tasks.$sequenceNumber'

const authRouteImport = createFileRoute('/(auth)')()
const appRouteImport = createFileRoute('/(app)')()
const appUnauthorizedLazyRouteImport = createFileRoute('/(app)/unauthorized')()
const appTermsLazyRouteImport = createFileRoute('/(app)/terms')()
const appStatusLazyRouteImport = createFileRoute('/(app)/status')()
const appPrivacyLazyRouteImport = createFileRoute('/(app)/privacy')()
const appExamplesQueryLazyRouteImport = createFileRoute(
  '/(app)/_examples/query',
)()
const appExamplesFormLazyRouteImport = createFileRoute(
  '/(app)/_examples/form',
)()
const appExamplesDemoLazyRouteImport = createFileRoute(
  '/(app)/_examples/demo_',
)()
const appExamplesDemoTypographyLazyRouteImport = createFileRoute(
  '/(app)/_examples/demo/typography',
)()
const appExamplesDemoTablesLazyRouteImport = createFileRoute(
  '/(app)/_examples/demo/tables',
)()
const appExamplesDemoNavigationLazyRouteImport = createFileRoute(
  '/(app)/_examples/demo/navigation',
)()
const appExamplesDemoLoadersLazyRouteImport = createFileRoute(
  '/(app)/_examples/demo/loaders',
)()
const appExamplesDemoFormsLazyRouteImport = createFileRoute(
  '/(app)/_examples/demo/forms',
)()
const appExamplesDemoDatabaseLazyRouteImport = createFileRoute(
  '/(app)/_examples/demo/database',
)()
const appExamplesDemoContainersLazyRouteImport = createFileRoute(
  '/(app)/_examples/demo/containers',
)()
const appExamplesDemoColorsLazyRouteImport = createFileRoute(
  '/(app)/_examples/demo/colors',
)()
const appExamplesDemoBasicLazyRouteImport = createFileRoute(
  '/(app)/_examples/demo/basic',
)()

const authRoute = authRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRoute = appRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appUnauthorizedLazyRoute = appUnauthorizedLazyRouteImport
  .update({
    id: '/unauthorized',
    path: '/unauthorized',
    getParentRoute: () => appRoute,
  } as any)
  .lazy(() => import('./routes/(app)/unauthorized.lazy').then((d) => d.Route))
const appTermsLazyRoute = appTermsLazyRouteImport
  .update({
    id: '/terms',
    path: '/terms',
    getParentRoute: () => appRoute,
  } as any)
  .lazy(() => import('./routes/(app)/terms.lazy').then((d) => d.Route))
const appStatusLazyRoute = appStatusLazyRouteImport
  .update({
    id: '/status',
    path: '/status',
    getParentRoute: () => appRoute,
  } as any)
  .lazy(() => import('./routes/(app)/status.lazy').then((d) => d.Route))
const appPrivacyLazyRoute = appPrivacyLazyRouteImport
  .update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => appRoute,
  } as any)
  .lazy(() => import('./routes/(app)/privacy.lazy').then((d) => d.Route))
const testTestRoute = testTestRouteImport.update({
  id: '/(test)/test_',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRoute,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => authRoute,
} as any)
const appParentsRoute = appParentsRouteImport.update({
  id: '/_parents',
  getParentRoute: () => appRoute,
} as any)
const appKidsRoute = appKidsRouteImport.update({
  id: '/_kids',
  getParentRoute: () => appRoute,
} as any)
const appExamplesRoute = appExamplesRouteImport.update({
  id: '/_examples',
  getParentRoute: () => appRoute,
} as any)
const appAdminRoute = appAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => appRoute,
} as any)
const appExamplesQueryLazyRoute = appExamplesQueryLazyRouteImport
  .update({
    id: '/query',
    path: '/query',
    getParentRoute: () => appExamplesRoute,
  } as any)
  .lazy(() =>
    import('./routes/(app)/_examples/query.lazy').then((d) => d.Route),
  )
const appExamplesFormLazyRoute = appExamplesFormLazyRouteImport
  .update({
    id: '/form',
    path: '/form',
    getParentRoute: () => appExamplesRoute,
  } as any)
  .lazy(() => import('./routes/(app)/_examples/form.lazy').then((d) => d.Route))
const appExamplesDemoLazyRoute = appExamplesDemoLazyRouteImport
  .update({
    id: '/demo_',
    path: '/demo',
    getParentRoute: () => appExamplesRoute,
  } as any)
  .lazy(() =>
    import('./routes/(app)/_examples/demo_.lazy').then((d) => d.Route),
  )
const testTestARoute = testTestARouteImport.update({
  id: '/(test)/test/a_',
  path: '/test/a',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthProfileRoute = authAuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => authAuthRoute,
} as any)
const appParentsParentsIndexRoute = appParentsParentsIndexRouteImport.update({
  id: '/parents/',
  path: '/parents/',
  getParentRoute: () => appParentsRoute,
} as any)
const appKidsKidsIndexRoute = appKidsKidsIndexRouteImport.update({
  id: '/kids/',
  path: '/kids/',
  getParentRoute: () => appKidsRoute,
} as any)
const appAdminAdminIndexRoute = appAdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => appAdminRoute,
} as any)
const appExamplesDemoTypographyLazyRoute =
  appExamplesDemoTypographyLazyRouteImport
    .update({
      id: '/demo/typography',
      path: '/demo/typography',
      getParentRoute: () => appExamplesRoute,
    } as any)
    .lazy(() =>
      import('./routes/(app)/_examples/demo.typography.lazy').then(
        (d) => d.Route,
      ),
    )
const appExamplesDemoTablesLazyRoute = appExamplesDemoTablesLazyRouteImport
  .update({
    id: '/demo/tables',
    path: '/demo/tables',
    getParentRoute: () => appExamplesRoute,
  } as any)
  .lazy(() =>
    import('./routes/(app)/_examples/demo.tables.lazy').then((d) => d.Route),
  )
const appExamplesDemoNavigationLazyRoute =
  appExamplesDemoNavigationLazyRouteImport
    .update({
      id: '/demo/navigation',
      path: '/demo/navigation',
      getParentRoute: () => appExamplesRoute,
    } as any)
    .lazy(() =>
      import('./routes/(app)/_examples/demo.navigation.lazy').then(
        (d) => d.Route,
      ),
    )
const appExamplesDemoLoadersLazyRoute = appExamplesDemoLoadersLazyRouteImport
  .update({
    id: '/demo/loaders',
    path: '/demo/loaders',
    getParentRoute: () => appExamplesRoute,
  } as any)
  .lazy(() =>
    import('./routes/(app)/_examples/demo.loaders.lazy').then((d) => d.Route),
  )
const appExamplesDemoFormsLazyRoute = appExamplesDemoFormsLazyRouteImport
  .update({
    id: '/demo/forms',
    path: '/demo/forms',
    getParentRoute: () => appExamplesRoute,
  } as any)
  .lazy(() =>
    import('./routes/(app)/_examples/demo.forms.lazy').then((d) => d.Route),
  )
const appExamplesDemoDatabaseLazyRoute = appExamplesDemoDatabaseLazyRouteImport
  .update({
    id: '/demo/database',
    path: '/demo/database',
    getParentRoute: () => appExamplesRoute,
  } as any)
  .lazy(() =>
    import('./routes/(app)/_examples/demo.database.lazy').then((d) => d.Route),
  )
const appExamplesDemoContainersLazyRoute =
  appExamplesDemoContainersLazyRouteImport
    .update({
      id: '/demo/containers',
      path: '/demo/containers',
      getParentRoute: () => appExamplesRoute,
    } as any)
    .lazy(() =>
      import('./routes/(app)/_examples/demo.containers.lazy').then(
        (d) => d.Route,
      ),
    )
const appExamplesDemoColorsLazyRoute = appExamplesDemoColorsLazyRouteImport
  .update({
    id: '/demo/colors',
    path: '/demo/colors',
    getParentRoute: () => appExamplesRoute,
  } as any)
  .lazy(() =>
    import('./routes/(app)/_examples/demo.colors.lazy').then((d) => d.Route),
  )
const appExamplesDemoBasicLazyRoute = appExamplesDemoBasicLazyRouteImport
  .update({
    id: '/demo/basic',
    path: '/demo/basic',
    getParentRoute: () => appExamplesRoute,
  } as any)
  .lazy(() =>
    import('./routes/(app)/_examples/demo.basic.lazy').then((d) => d.Route),
  )
const testTestASomethingRoute = testTestASomethingRouteImport.update({
  id: '/(test)/test/a/something',
  path: '/test/a/something',
  getParentRoute: () => rootRouteImport,
} as any)
const testTestABRoute = testTestABRouteImport.update({
  id: '/(test)/test/a/b_',
  path: '/test/a/b',
  getParentRoute: () => rootRouteImport,
} as any)
const appParentsParentsTasksRoute = appParentsParentsTasksRouteImport.update({
  id: '/parents/tasks_',
  path: '/parents/tasks',
  getParentRoute: () => appParentsRoute,
} as any)
const appParentsParentsRoutinesRoute =
  appParentsParentsRoutinesRouteImport.update({
    id: '/parents/routines',
    path: '/parents/routines',
    getParentRoute: () => appParentsRoute,
  } as any)
const appParentsParentsRewardsRoute =
  appParentsParentsRewardsRouteImport.update({
    id: '/parents/rewards_',
    path: '/parents/rewards',
    getParentRoute: () => appParentsRoute,
  } as any)
const appParentsParentsApprovalsRoute =
  appParentsParentsApprovalsRouteImport.update({
    id: '/parents/approvals',
    path: '/parents/approvals',
    getParentRoute: () => appParentsRoute,
  } as any)
const appParentsParentsAchievementsRoute =
  appParentsParentsAchievementsRouteImport.update({
    id: '/parents/achievements',
    path: '/parents/achievements',
    getParentRoute: () => appParentsRoute,
  } as any)
const appKidsKidsPlayRoute = appKidsKidsPlayRouteImport.update({
  id: '/kids/play',
  path: '/kids/play',
  getParentRoute: () => appKidsRoute,
} as any)
const appKidsKidsHelpRoute = appKidsKidsHelpRouteImport.update({
  id: '/kids/help',
  path: '/kids/help',
  getParentRoute: () => appKidsRoute,
} as any)
const appKidsKidsFitnessRoute = appKidsKidsFitnessRouteImport.update({
  id: '/kids/fitness',
  path: '/kids/fitness',
  getParentRoute: () => appKidsRoute,
} as any)
const appKidsKidsEarnRoute = appKidsKidsEarnRouteImport.update({
  id: '/kids/earn',
  path: '/kids/earn',
  getParentRoute: () => appKidsRoute,
} as any)
const appExamplesDemoTestingRoute = appExamplesDemoTestingRouteImport.update({
  id: '/demo/testing',
  path: '/demo/testing',
  getParentRoute: () => appExamplesRoute,
} as any)
const appExamplesDemoDialogsRoute = appExamplesDemoDialogsRouteImport.update({
  id: '/demo/dialogs',
  path: '/demo/dialogs',
  getParentRoute: () => appExamplesRoute,
} as any)
const appAdminAdminUsersRoute = appAdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => appAdminRoute,
} as any)
const appAdminAdminAnalyticsRoute = appAdminAdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => appAdminRoute,
} as any)
const testTestABCRoute = testTestABCRouteImport.update({
  id: '/(test)/test/a/b/c',
  path: '/test/a/b/c',
  getParentRoute: () => rootRouteImport,
} as any)
const appParentsParentsTasksSequenceNumberRoute =
  appParentsParentsTasksSequenceNumberRouteImport.update({
    id: '/parents/tasks/$sequenceNumber',
    path: '/parents/tasks/$sequenceNumber',
    getParentRoute: () => appParentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof authAuthRouteWithChildren
  '/login': typeof authLoginRoute
  '/test': typeof testTestRoute
  '/privacy': typeof appPrivacyLazyRoute
  '/status': typeof appStatusLazyRoute
  '/terms': typeof appTermsLazyRoute
  '/unauthorized': typeof appUnauthorizedLazyRoute
  '/profile': typeof authAuthProfileRoute
  '/test/a': typeof testTestARoute
  '/demo': typeof appExamplesDemoLazyRoute
  '/form': typeof appExamplesFormLazyRoute
  '/query': typeof appExamplesQueryLazyRoute
  '/admin/analytics': typeof appAdminAdminAnalyticsRoute
  '/admin/users': typeof appAdminAdminUsersRoute
  '/demo/dialogs': typeof appExamplesDemoDialogsRoute
  '/demo/testing': typeof appExamplesDemoTestingRoute
  '/kids/earn': typeof appKidsKidsEarnRoute
  '/kids/fitness': typeof appKidsKidsFitnessRoute
  '/kids/help': typeof appKidsKidsHelpRoute
  '/kids/play': typeof appKidsKidsPlayRoute
  '/parents/achievements': typeof appParentsParentsAchievementsRoute
  '/parents/approvals': typeof appParentsParentsApprovalsRoute
  '/parents/rewards': typeof appParentsParentsRewardsRoute
  '/parents/routines': typeof appParentsParentsRoutinesRoute
  '/parents/tasks': typeof appParentsParentsTasksRoute
  '/test/a/b': typeof testTestABRoute
  '/test/a/something': typeof testTestASomethingRoute
  '/demo/basic': typeof appExamplesDemoBasicLazyRoute
  '/demo/colors': typeof appExamplesDemoColorsLazyRoute
  '/demo/containers': typeof appExamplesDemoContainersLazyRoute
  '/demo/database': typeof appExamplesDemoDatabaseLazyRoute
  '/demo/forms': typeof appExamplesDemoFormsLazyRoute
  '/demo/loaders': typeof appExamplesDemoLoadersLazyRoute
  '/demo/navigation': typeof appExamplesDemoNavigationLazyRoute
  '/demo/tables': typeof appExamplesDemoTablesLazyRoute
  '/demo/typography': typeof appExamplesDemoTypographyLazyRoute
  '/admin': typeof appAdminAdminIndexRoute
  '/kids': typeof appKidsKidsIndexRoute
  '/parents': typeof appParentsParentsIndexRoute
  '/parents/tasks/$sequenceNumber': typeof appParentsParentsTasksSequenceNumberRoute
  '/test/a/b/c': typeof testTestABCRoute
}
export interface FileRoutesByTo {
  '/': typeof authAuthRouteWithChildren
  '/login': typeof authLoginRoute
  '/test': typeof testTestRoute
  '/privacy': typeof appPrivacyLazyRoute
  '/status': typeof appStatusLazyRoute
  '/terms': typeof appTermsLazyRoute
  '/unauthorized': typeof appUnauthorizedLazyRoute
  '/profile': typeof authAuthProfileRoute
  '/test/a': typeof testTestARoute
  '/demo': typeof appExamplesDemoLazyRoute
  '/form': typeof appExamplesFormLazyRoute
  '/query': typeof appExamplesQueryLazyRoute
  '/admin/analytics': typeof appAdminAdminAnalyticsRoute
  '/admin/users': typeof appAdminAdminUsersRoute
  '/demo/dialogs': typeof appExamplesDemoDialogsRoute
  '/demo/testing': typeof appExamplesDemoTestingRoute
  '/kids/earn': typeof appKidsKidsEarnRoute
  '/kids/fitness': typeof appKidsKidsFitnessRoute
  '/kids/help': typeof appKidsKidsHelpRoute
  '/kids/play': typeof appKidsKidsPlayRoute
  '/parents/achievements': typeof appParentsParentsAchievementsRoute
  '/parents/approvals': typeof appParentsParentsApprovalsRoute
  '/parents/rewards': typeof appParentsParentsRewardsRoute
  '/parents/routines': typeof appParentsParentsRoutinesRoute
  '/parents/tasks': typeof appParentsParentsTasksRoute
  '/test/a/b': typeof testTestABRoute
  '/test/a/something': typeof testTestASomethingRoute
  '/demo/basic': typeof appExamplesDemoBasicLazyRoute
  '/demo/colors': typeof appExamplesDemoColorsLazyRoute
  '/demo/containers': typeof appExamplesDemoContainersLazyRoute
  '/demo/database': typeof appExamplesDemoDatabaseLazyRoute
  '/demo/forms': typeof appExamplesDemoFormsLazyRoute
  '/demo/loaders': typeof appExamplesDemoLoadersLazyRoute
  '/demo/navigation': typeof appExamplesDemoNavigationLazyRoute
  '/demo/tables': typeof appExamplesDemoTablesLazyRoute
  '/demo/typography': typeof appExamplesDemoTypographyLazyRoute
  '/admin': typeof appAdminAdminIndexRoute
  '/kids': typeof appKidsKidsIndexRoute
  '/parents': typeof appParentsParentsIndexRoute
  '/parents/tasks/$sequenceNumber': typeof appParentsParentsTasksSequenceNumberRoute
  '/test/a/b/c': typeof testTestABCRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteWithChildren
  '/(app)/_admin': typeof appAdminRouteWithChildren
  '/(app)/_examples': typeof appExamplesRouteWithChildren
  '/(app)/_kids': typeof appKidsRouteWithChildren
  '/(app)/_parents': typeof appParentsRouteWithChildren
  '/(auth)': typeof authRouteWithChildren
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(test)/test_': typeof testTestRoute
  '/(app)/privacy': typeof appPrivacyLazyRoute
  '/(app)/status': typeof appStatusLazyRoute
  '/(app)/terms': typeof appTermsLazyRoute
  '/(app)/unauthorized': typeof appUnauthorizedLazyRoute
  '/(auth)/_auth/profile': typeof authAuthProfileRoute
  '/(test)/test/a_': typeof testTestARoute
  '/(app)/_examples/demo_': typeof appExamplesDemoLazyRoute
  '/(app)/_examples/form': typeof appExamplesFormLazyRoute
  '/(app)/_examples/query': typeof appExamplesQueryLazyRoute
  '/(app)/_admin/admin/analytics': typeof appAdminAdminAnalyticsRoute
  '/(app)/_admin/admin/users': typeof appAdminAdminUsersRoute
  '/(app)/_examples/demo/dialogs': typeof appExamplesDemoDialogsRoute
  '/(app)/_examples/demo/testing': typeof appExamplesDemoTestingRoute
  '/(app)/_kids/kids/earn': typeof appKidsKidsEarnRoute
  '/(app)/_kids/kids/fitness': typeof appKidsKidsFitnessRoute
  '/(app)/_kids/kids/help': typeof appKidsKidsHelpRoute
  '/(app)/_kids/kids/play': typeof appKidsKidsPlayRoute
  '/(app)/_parents/parents/achievements': typeof appParentsParentsAchievementsRoute
  '/(app)/_parents/parents/approvals': typeof appParentsParentsApprovalsRoute
  '/(app)/_parents/parents/rewards_': typeof appParentsParentsRewardsRoute
  '/(app)/_parents/parents/routines': typeof appParentsParentsRoutinesRoute
  '/(app)/_parents/parents/tasks_': typeof appParentsParentsTasksRoute
  '/(test)/test/a/b_': typeof testTestABRoute
  '/(test)/test/a/something': typeof testTestASomethingRoute
  '/(app)/_examples/demo/basic': typeof appExamplesDemoBasicLazyRoute
  '/(app)/_examples/demo/colors': typeof appExamplesDemoColorsLazyRoute
  '/(app)/_examples/demo/containers': typeof appExamplesDemoContainersLazyRoute
  '/(app)/_examples/demo/database': typeof appExamplesDemoDatabaseLazyRoute
  '/(app)/_examples/demo/forms': typeof appExamplesDemoFormsLazyRoute
  '/(app)/_examples/demo/loaders': typeof appExamplesDemoLoadersLazyRoute
  '/(app)/_examples/demo/navigation': typeof appExamplesDemoNavigationLazyRoute
  '/(app)/_examples/demo/tables': typeof appExamplesDemoTablesLazyRoute
  '/(app)/_examples/demo/typography': typeof appExamplesDemoTypographyLazyRoute
  '/(app)/_admin/admin/': typeof appAdminAdminIndexRoute
  '/(app)/_kids/kids/': typeof appKidsKidsIndexRoute
  '/(app)/_parents/parents/': typeof appParentsParentsIndexRoute
  '/(app)/_parents/parents/tasks/$sequenceNumber': typeof appParentsParentsTasksSequenceNumberRoute
  '/(test)/test/a/b/c': typeof testTestABCRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/test'
    | '/privacy'
    | '/status'
    | '/terms'
    | '/unauthorized'
    | '/profile'
    | '/test/a'
    | '/demo'
    | '/form'
    | '/query'
    | '/admin/analytics'
    | '/admin/users'
    | '/demo/dialogs'
    | '/demo/testing'
    | '/kids/earn'
    | '/kids/fitness'
    | '/kids/help'
    | '/kids/play'
    | '/parents/achievements'
    | '/parents/approvals'
    | '/parents/rewards'
    | '/parents/routines'
    | '/parents/tasks'
    | '/test/a/b'
    | '/test/a/something'
    | '/demo/basic'
    | '/demo/colors'
    | '/demo/containers'
    | '/demo/database'
    | '/demo/forms'
    | '/demo/loaders'
    | '/demo/navigation'
    | '/demo/tables'
    | '/demo/typography'
    | '/admin'
    | '/kids'
    | '/parents'
    | '/parents/tasks/$sequenceNumber'
    | '/test/a/b/c'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/test'
    | '/privacy'
    | '/status'
    | '/terms'
    | '/unauthorized'
    | '/profile'
    | '/test/a'
    | '/demo'
    | '/form'
    | '/query'
    | '/admin/analytics'
    | '/admin/users'
    | '/demo/dialogs'
    | '/demo/testing'
    | '/kids/earn'
    | '/kids/fitness'
    | '/kids/help'
    | '/kids/play'
    | '/parents/achievements'
    | '/parents/approvals'
    | '/parents/rewards'
    | '/parents/routines'
    | '/parents/tasks'
    | '/test/a/b'
    | '/test/a/something'
    | '/demo/basic'
    | '/demo/colors'
    | '/demo/containers'
    | '/demo/database'
    | '/demo/forms'
    | '/demo/loaders'
    | '/demo/navigation'
    | '/demo/tables'
    | '/demo/typography'
    | '/admin'
    | '/kids'
    | '/parents'
    | '/parents/tasks/$sequenceNumber'
    | '/test/a/b/c'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(app)/_admin'
    | '/(app)/_examples'
    | '/(app)/_kids'
    | '/(app)/_parents'
    | '/(auth)'
    | '/(auth)/_auth'
    | '/(auth)/login'
    | '/(test)/test_'
    | '/(app)/privacy'
    | '/(app)/status'
    | '/(app)/terms'
    | '/(app)/unauthorized'
    | '/(auth)/_auth/profile'
    | '/(test)/test/a_'
    | '/(app)/_examples/demo_'
    | '/(app)/_examples/form'
    | '/(app)/_examples/query'
    | '/(app)/_admin/admin/analytics'
    | '/(app)/_admin/admin/users'
    | '/(app)/_examples/demo/dialogs'
    | '/(app)/_examples/demo/testing'
    | '/(app)/_kids/kids/earn'
    | '/(app)/_kids/kids/fitness'
    | '/(app)/_kids/kids/help'
    | '/(app)/_kids/kids/play'
    | '/(app)/_parents/parents/achievements'
    | '/(app)/_parents/parents/approvals'
    | '/(app)/_parents/parents/rewards_'
    | '/(app)/_parents/parents/routines'
    | '/(app)/_parents/parents/tasks_'
    | '/(test)/test/a/b_'
    | '/(test)/test/a/something'
    | '/(app)/_examples/demo/basic'
    | '/(app)/_examples/demo/colors'
    | '/(app)/_examples/demo/containers'
    | '/(app)/_examples/demo/database'
    | '/(app)/_examples/demo/forms'
    | '/(app)/_examples/demo/loaders'
    | '/(app)/_examples/demo/navigation'
    | '/(app)/_examples/demo/tables'
    | '/(app)/_examples/demo/typography'
    | '/(app)/_admin/admin/'
    | '/(app)/_kids/kids/'
    | '/(app)/_parents/parents/'
    | '/(app)/_parents/parents/tasks/$sequenceNumber'
    | '/(test)/test/a/b/c'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRoute: typeof appRouteWithChildren
  authRoute: typeof authRouteWithChildren
  testTestRoute: typeof testTestRoute
  testTestARoute: typeof testTestARoute
  testTestABRoute: typeof testTestABRoute
  testTestASomethingRoute: typeof testTestASomethingRoute
  testTestABCRoute: typeof testTestABCRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/unauthorized': {
      id: '/(app)/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof appUnauthorizedLazyRouteImport
      parentRoute: typeof appRoute
    }
    '/(app)/terms': {
      id: '/(app)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof appTermsLazyRouteImport
      parentRoute: typeof appRoute
    }
    '/(app)/status': {
      id: '/(app)/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof appStatusLazyRouteImport
      parentRoute: typeof appRoute
    }
    '/(app)/privacy': {
      id: '/(app)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof appPrivacyLazyRouteImport
      parentRoute: typeof appRoute
    }
    '/(test)/test_': {
      id: '/(test)/test_'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof testTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRoute
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof authRoute
    }
    '/(app)/_parents': {
      id: '/(app)/_parents'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appParentsRouteImport
      parentRoute: typeof appRoute
    }
    '/(app)/_kids': {
      id: '/(app)/_kids'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appKidsRouteImport
      parentRoute: typeof appRoute
    }
    '/(app)/_examples': {
      id: '/(app)/_examples'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appExamplesRouteImport
      parentRoute: typeof appRoute
    }
    '/(app)/_admin': {
      id: '/(app)/_admin'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appAdminRouteImport
      parentRoute: typeof appRoute
    }
    '/(app)/_examples/query': {
      id: '/(app)/_examples/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof appExamplesQueryLazyRouteImport
      parentRoute: typeof appExamplesRoute
    }
    '/(app)/_examples/form': {
      id: '/(app)/_examples/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof appExamplesFormLazyRouteImport
      parentRoute: typeof appExamplesRoute
    }
    '/(app)/_examples/demo_': {
      id: '/(app)/_examples/demo_'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof appExamplesDemoLazyRouteImport
      parentRoute: typeof appExamplesRoute
    }
    '/(test)/test/a_': {
      id: '/(test)/test/a_'
      path: '/test/a'
      fullPath: '/test/a'
      preLoaderRoute: typeof testTestARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth/profile': {
      id: '/(auth)/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof authAuthProfileRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(app)/_parents/parents/': {
      id: '/(app)/_parents/parents/'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof appParentsParentsIndexRouteImport
      parentRoute: typeof appParentsRoute
    }
    '/(app)/_kids/kids/': {
      id: '/(app)/_kids/kids/'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof appKidsKidsIndexRouteImport
      parentRoute: typeof appKidsRoute
    }
    '/(app)/_admin/admin/': {
      id: '/(app)/_admin/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof appAdminAdminIndexRouteImport
      parentRoute: typeof appAdminRoute
    }
    '/(app)/_examples/demo/typography': {
      id: '/(app)/_examples/demo/typography'
      path: '/demo/typography'
      fullPath: '/demo/typography'
      preLoaderRoute: typeof appExamplesDemoTypographyLazyRouteImport
      parentRoute: typeof appExamplesRoute
    }
    '/(app)/_examples/demo/tables': {
      id: '/(app)/_examples/demo/tables'
      path: '/demo/tables'
      fullPath: '/demo/tables'
      preLoaderRoute: typeof appExamplesDemoTablesLazyRouteImport
      parentRoute: typeof appExamplesRoute
    }
    '/(app)/_examples/demo/navigation': {
      id: '/(app)/_examples/demo/navigation'
      path: '/demo/navigation'
      fullPath: '/demo/navigation'
      preLoaderRoute: typeof appExamplesDemoNavigationLazyRouteImport
      parentRoute: typeof appExamplesRoute
    }
    '/(app)/_examples/demo/loaders': {
      id: '/(app)/_examples/demo/loaders'
      path: '/demo/loaders'
      fullPath: '/demo/loaders'
      preLoaderRoute: typeof appExamplesDemoLoadersLazyRouteImport
      parentRoute: typeof appExamplesRoute
    }
    '/(app)/_examples/demo/forms': {
      id: '/(app)/_examples/demo/forms'
      path: '/demo/forms'
      fullPath: '/demo/forms'
      preLoaderRoute: typeof appExamplesDemoFormsLazyRouteImport
      parentRoute: typeof appExamplesRoute
    }
    '/(app)/_examples/demo/database': {
      id: '/(app)/_examples/demo/database'
      path: '/demo/database'
      fullPath: '/demo/database'
      preLoaderRoute: typeof appExamplesDemoDatabaseLazyRouteImport
      parentRoute: typeof appExamplesRoute
    }
    '/(app)/_examples/demo/containers': {
      id: '/(app)/_examples/demo/containers'
      path: '/demo/containers'
      fullPath: '/demo/containers'
      preLoaderRoute: typeof appExamplesDemoContainersLazyRouteImport
      parentRoute: typeof appExamplesRoute
    }
    '/(app)/_examples/demo/colors': {
      id: '/(app)/_examples/demo/colors'
      path: '/demo/colors'
      fullPath: '/demo/colors'
      preLoaderRoute: typeof appExamplesDemoColorsLazyRouteImport
      parentRoute: typeof appExamplesRoute
    }
    '/(app)/_examples/demo/basic': {
      id: '/(app)/_examples/demo/basic'
      path: '/demo/basic'
      fullPath: '/demo/basic'
      preLoaderRoute: typeof appExamplesDemoBasicLazyRouteImport
      parentRoute: typeof appExamplesRoute
    }
    '/(test)/test/a/something': {
      id: '/(test)/test/a/something'
      path: '/test/a/something'
      fullPath: '/test/a/something'
      preLoaderRoute: typeof testTestASomethingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(test)/test/a/b_': {
      id: '/(test)/test/a/b_'
      path: '/test/a/b'
      fullPath: '/test/a/b'
      preLoaderRoute: typeof testTestABRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_parents/parents/tasks_': {
      id: '/(app)/_parents/parents/tasks_'
      path: '/parents/tasks'
      fullPath: '/parents/tasks'
      preLoaderRoute: typeof appParentsParentsTasksRouteImport
      parentRoute: typeof appParentsRoute
    }
    '/(app)/_parents/parents/routines': {
      id: '/(app)/_parents/parents/routines'
      path: '/parents/routines'
      fullPath: '/parents/routines'
      preLoaderRoute: typeof appParentsParentsRoutinesRouteImport
      parentRoute: typeof appParentsRoute
    }
    '/(app)/_parents/parents/rewards_': {
      id: '/(app)/_parents/parents/rewards_'
      path: '/parents/rewards'
      fullPath: '/parents/rewards'
      preLoaderRoute: typeof appParentsParentsRewardsRouteImport
      parentRoute: typeof appParentsRoute
    }
    '/(app)/_parents/parents/approvals': {
      id: '/(app)/_parents/parents/approvals'
      path: '/parents/approvals'
      fullPath: '/parents/approvals'
      preLoaderRoute: typeof appParentsParentsApprovalsRouteImport
      parentRoute: typeof appParentsRoute
    }
    '/(app)/_parents/parents/achievements': {
      id: '/(app)/_parents/parents/achievements'
      path: '/parents/achievements'
      fullPath: '/parents/achievements'
      preLoaderRoute: typeof appParentsParentsAchievementsRouteImport
      parentRoute: typeof appParentsRoute
    }
    '/(app)/_kids/kids/play': {
      id: '/(app)/_kids/kids/play'
      path: '/kids/play'
      fullPath: '/kids/play'
      preLoaderRoute: typeof appKidsKidsPlayRouteImport
      parentRoute: typeof appKidsRoute
    }
    '/(app)/_kids/kids/help': {
      id: '/(app)/_kids/kids/help'
      path: '/kids/help'
      fullPath: '/kids/help'
      preLoaderRoute: typeof appKidsKidsHelpRouteImport
      parentRoute: typeof appKidsRoute
    }
    '/(app)/_kids/kids/fitness': {
      id: '/(app)/_kids/kids/fitness'
      path: '/kids/fitness'
      fullPath: '/kids/fitness'
      preLoaderRoute: typeof appKidsKidsFitnessRouteImport
      parentRoute: typeof appKidsRoute
    }
    '/(app)/_kids/kids/earn': {
      id: '/(app)/_kids/kids/earn'
      path: '/kids/earn'
      fullPath: '/kids/earn'
      preLoaderRoute: typeof appKidsKidsEarnRouteImport
      parentRoute: typeof appKidsRoute
    }
    '/(app)/_examples/demo/testing': {
      id: '/(app)/_examples/demo/testing'
      path: '/demo/testing'
      fullPath: '/demo/testing'
      preLoaderRoute: typeof appExamplesDemoTestingRouteImport
      parentRoute: typeof appExamplesRoute
    }
    '/(app)/_examples/demo/dialogs': {
      id: '/(app)/_examples/demo/dialogs'
      path: '/demo/dialogs'
      fullPath: '/demo/dialogs'
      preLoaderRoute: typeof appExamplesDemoDialogsRouteImport
      parentRoute: typeof appExamplesRoute
    }
    '/(app)/_admin/admin/users': {
      id: '/(app)/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof appAdminAdminUsersRouteImport
      parentRoute: typeof appAdminRoute
    }
    '/(app)/_admin/admin/analytics': {
      id: '/(app)/_admin/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof appAdminAdminAnalyticsRouteImport
      parentRoute: typeof appAdminRoute
    }
    '/(test)/test/a/b/c': {
      id: '/(test)/test/a/b/c'
      path: '/test/a/b/c'
      fullPath: '/test/a/b/c'
      preLoaderRoute: typeof testTestABCRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_parents/parents/tasks/$sequenceNumber': {
      id: '/(app)/_parents/parents/tasks/$sequenceNumber'
      path: '/parents/tasks/$sequenceNumber'
      fullPath: '/parents/tasks/$sequenceNumber'
      preLoaderRoute: typeof appParentsParentsTasksSequenceNumberRouteImport
      parentRoute: typeof appParentsRoute
    }
  }
}

interface appAdminRouteChildren {
  appAdminAdminAnalyticsRoute: typeof appAdminAdminAnalyticsRoute
  appAdminAdminUsersRoute: typeof appAdminAdminUsersRoute
  appAdminAdminIndexRoute: typeof appAdminAdminIndexRoute
}

const appAdminRouteChildren: appAdminRouteChildren = {
  appAdminAdminAnalyticsRoute: appAdminAdminAnalyticsRoute,
  appAdminAdminUsersRoute: appAdminAdminUsersRoute,
  appAdminAdminIndexRoute: appAdminAdminIndexRoute,
}

const appAdminRouteWithChildren = appAdminRoute._addFileChildren(
  appAdminRouteChildren,
)

interface appExamplesRouteChildren {
  appExamplesDemoLazyRoute: typeof appExamplesDemoLazyRoute
  appExamplesFormLazyRoute: typeof appExamplesFormLazyRoute
  appExamplesQueryLazyRoute: typeof appExamplesQueryLazyRoute
  appExamplesDemoDialogsRoute: typeof appExamplesDemoDialogsRoute
  appExamplesDemoTestingRoute: typeof appExamplesDemoTestingRoute
  appExamplesDemoBasicLazyRoute: typeof appExamplesDemoBasicLazyRoute
  appExamplesDemoColorsLazyRoute: typeof appExamplesDemoColorsLazyRoute
  appExamplesDemoContainersLazyRoute: typeof appExamplesDemoContainersLazyRoute
  appExamplesDemoDatabaseLazyRoute: typeof appExamplesDemoDatabaseLazyRoute
  appExamplesDemoFormsLazyRoute: typeof appExamplesDemoFormsLazyRoute
  appExamplesDemoLoadersLazyRoute: typeof appExamplesDemoLoadersLazyRoute
  appExamplesDemoNavigationLazyRoute: typeof appExamplesDemoNavigationLazyRoute
  appExamplesDemoTablesLazyRoute: typeof appExamplesDemoTablesLazyRoute
  appExamplesDemoTypographyLazyRoute: typeof appExamplesDemoTypographyLazyRoute
}

const appExamplesRouteChildren: appExamplesRouteChildren = {
  appExamplesDemoLazyRoute: appExamplesDemoLazyRoute,
  appExamplesFormLazyRoute: appExamplesFormLazyRoute,
  appExamplesQueryLazyRoute: appExamplesQueryLazyRoute,
  appExamplesDemoDialogsRoute: appExamplesDemoDialogsRoute,
  appExamplesDemoTestingRoute: appExamplesDemoTestingRoute,
  appExamplesDemoBasicLazyRoute: appExamplesDemoBasicLazyRoute,
  appExamplesDemoColorsLazyRoute: appExamplesDemoColorsLazyRoute,
  appExamplesDemoContainersLazyRoute: appExamplesDemoContainersLazyRoute,
  appExamplesDemoDatabaseLazyRoute: appExamplesDemoDatabaseLazyRoute,
  appExamplesDemoFormsLazyRoute: appExamplesDemoFormsLazyRoute,
  appExamplesDemoLoadersLazyRoute: appExamplesDemoLoadersLazyRoute,
  appExamplesDemoNavigationLazyRoute: appExamplesDemoNavigationLazyRoute,
  appExamplesDemoTablesLazyRoute: appExamplesDemoTablesLazyRoute,
  appExamplesDemoTypographyLazyRoute: appExamplesDemoTypographyLazyRoute,
}

const appExamplesRouteWithChildren = appExamplesRoute._addFileChildren(
  appExamplesRouteChildren,
)

interface appKidsRouteChildren {
  appKidsKidsEarnRoute: typeof appKidsKidsEarnRoute
  appKidsKidsFitnessRoute: typeof appKidsKidsFitnessRoute
  appKidsKidsHelpRoute: typeof appKidsKidsHelpRoute
  appKidsKidsPlayRoute: typeof appKidsKidsPlayRoute
  appKidsKidsIndexRoute: typeof appKidsKidsIndexRoute
}

const appKidsRouteChildren: appKidsRouteChildren = {
  appKidsKidsEarnRoute: appKidsKidsEarnRoute,
  appKidsKidsFitnessRoute: appKidsKidsFitnessRoute,
  appKidsKidsHelpRoute: appKidsKidsHelpRoute,
  appKidsKidsPlayRoute: appKidsKidsPlayRoute,
  appKidsKidsIndexRoute: appKidsKidsIndexRoute,
}

const appKidsRouteWithChildren =
  appKidsRoute._addFileChildren(appKidsRouteChildren)

interface appParentsRouteChildren {
  appParentsParentsAchievementsRoute: typeof appParentsParentsAchievementsRoute
  appParentsParentsApprovalsRoute: typeof appParentsParentsApprovalsRoute
  appParentsParentsRewardsRoute: typeof appParentsParentsRewardsRoute
  appParentsParentsRoutinesRoute: typeof appParentsParentsRoutinesRoute
  appParentsParentsTasksRoute: typeof appParentsParentsTasksRoute
  appParentsParentsIndexRoute: typeof appParentsParentsIndexRoute
  appParentsParentsTasksSequenceNumberRoute: typeof appParentsParentsTasksSequenceNumberRoute
}

const appParentsRouteChildren: appParentsRouteChildren = {
  appParentsParentsAchievementsRoute: appParentsParentsAchievementsRoute,
  appParentsParentsApprovalsRoute: appParentsParentsApprovalsRoute,
  appParentsParentsRewardsRoute: appParentsParentsRewardsRoute,
  appParentsParentsRoutinesRoute: appParentsParentsRoutinesRoute,
  appParentsParentsTasksRoute: appParentsParentsTasksRoute,
  appParentsParentsIndexRoute: appParentsParentsIndexRoute,
  appParentsParentsTasksSequenceNumberRoute:
    appParentsParentsTasksSequenceNumberRoute,
}

const appParentsRouteWithChildren = appParentsRoute._addFileChildren(
  appParentsRouteChildren,
)

interface appRouteChildren {
  appAdminRoute: typeof appAdminRouteWithChildren
  appExamplesRoute: typeof appExamplesRouteWithChildren
  appKidsRoute: typeof appKidsRouteWithChildren
  appParentsRoute: typeof appParentsRouteWithChildren
  appPrivacyLazyRoute: typeof appPrivacyLazyRoute
  appStatusLazyRoute: typeof appStatusLazyRoute
  appTermsLazyRoute: typeof appTermsLazyRoute
  appUnauthorizedLazyRoute: typeof appUnauthorizedLazyRoute
}

const appRouteChildren: appRouteChildren = {
  appAdminRoute: appAdminRouteWithChildren,
  appExamplesRoute: appExamplesRouteWithChildren,
  appKidsRoute: appKidsRouteWithChildren,
  appParentsRoute: appParentsRouteWithChildren,
  appPrivacyLazyRoute: appPrivacyLazyRoute,
  appStatusLazyRoute: appStatusLazyRoute,
  appTermsLazyRoute: appTermsLazyRoute,
  appUnauthorizedLazyRoute: appUnauthorizedLazyRoute,
}

const appRouteWithChildren = appRoute._addFileChildren(appRouteChildren)

interface authAuthRouteChildren {
  authAuthProfileRoute: typeof authAuthProfileRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthProfileRoute: authAuthProfileRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

interface authRouteChildren {
  authAuthRoute: typeof authAuthRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

const authRouteChildren: authRouteChildren = {
  authAuthRoute: authAuthRouteWithChildren,
  authLoginRoute: authLoginRoute,
}

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRoute: appRouteWithChildren,
  authRoute: authRouteWithChildren,
  testTestRoute: testTestRoute,
  testTestARoute: testTestARoute,
  testTestABRoute: testTestABRoute,
  testTestASomethingRoute: testTestASomethingRoute,
  testTestABCRoute: testTestABCRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
