/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as testTestRouteImport } from './routes/(test)/test_'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authAuthRouteImport } from './routes/(auth)/_auth'
import { Route as appParentsRouteImport } from './routes/(app)/_parents'
import { Route as appKidsRouteImport } from './routes/(app)/_kids'
import { Route as appExamplesRouteImport } from './routes/(app)/_examples'
import { Route as appAdminRouteImport } from './routes/(app)/_admin'
import { Route as testTestARouteImport } from './routes/(test)/test.a_'
import { Route as authAuthProfileRouteImport } from './routes/(auth)/_auth.profile'
import { Route as appExamplesUiRouteImport } from './routes/(app)/_examples/ui_'
import { Route as appParentsParentsIndexRouteImport } from './routes/(app)/_parents/parents.index'
import { Route as appKidsKidsIndexRouteImport } from './routes/(app)/_kids/kids.index'
import { Route as appAdminAdminIndexRouteImport } from './routes/(app)/_admin/admin.index'
import { Route as testTestASomethingRouteImport } from './routes/(test)/test.a.something'
import { Route as testTestABRouteImport } from './routes/(test)/test.a.b_'
import { Route as appParentsParentsTasksRouteImport } from './routes/(app)/_parents/parents.tasks_'
import { Route as appParentsParentsRewardsRouteImport } from './routes/(app)/_parents/parents.rewards_'
import { Route as appParentsParentsApprovalsRouteImport } from './routes/(app)/_parents/parents.approvals'
import { Route as appParentsParentsAchievementsRouteImport } from './routes/(app)/_parents/parents.achievements'
import { Route as appKidsKidsPlayRouteImport } from './routes/(app)/_kids/kids.play'
import { Route as appKidsKidsHelpRouteImport } from './routes/(app)/_kids/kids.help'
import { Route as appKidsKidsFitnessRouteImport } from './routes/(app)/_kids/kids.fitness'
import { Route as appKidsKidsEarnRouteImport } from './routes/(app)/_kids/kids.earn'
import { Route as appExamplesUiCategoryRouteImport } from './routes/(app)/_examples/ui.$category'
import { Route as appAdminAdminUsersRouteImport } from './routes/(app)/_admin/admin.users'
import { Route as appAdminAdminAnalyticsRouteImport } from './routes/(app)/_admin/admin.analytics'
import { Route as testTestABCRouteImport } from './routes/(test)/test.a.b.c'
import { Route as appParentsParentsTasksNewRouteImport } from './routes/(app)/_parents/parents.tasks.new'
import { Route as appParentsParentsTasksSequenceNumberRouteImport } from './routes/(app)/_parents/parents.tasks.$sequenceNumber'

const appUnauthorizedLazyRouteImport = createFileRoute('/(app)/unauthorized')()
const appTermsLazyRouteImport = createFileRoute('/(app)/terms')()
const appStatusLazyRouteImport = createFileRoute('/(app)/status')()
const appPrivacyLazyRouteImport = createFileRoute('/(app)/privacy')()
const appExamplesQueryLazyRouteImport = createFileRoute(
  '/(app)/_examples/query',
)()
const appExamplesFormLazyRouteImport = createFileRoute(
  '/(app)/_examples/form',
)()
const appExamplesDemoTablesLazyRouteImport = createFileRoute(
  '/(app)/_examples/demo/tables',
)()
const appExamplesDemoDatabaseLazyRouteImport = createFileRoute(
  '/(app)/_examples/demo/database',
)()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appUnauthorizedLazyRoute = appUnauthorizedLazyRouteImport
  .update({
    id: '/(app)/unauthorized',
    path: '/unauthorized',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(app)/unauthorized.lazy').then((d) => d.Route))
const appTermsLazyRoute = appTermsLazyRouteImport
  .update({
    id: '/(app)/terms',
    path: '/terms',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(app)/terms.lazy').then((d) => d.Route))
const appStatusLazyRoute = appStatusLazyRouteImport
  .update({
    id: '/(app)/status',
    path: '/status',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(app)/status.lazy').then((d) => d.Route))
const appPrivacyLazyRoute = appPrivacyLazyRouteImport
  .update({
    id: '/(app)/privacy',
    path: '/privacy',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(app)/privacy.lazy').then((d) => d.Route))
const testTestRoute = testTestRouteImport.update({
  id: '/(test)/test_',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const appParentsRoute = appParentsRouteImport.update({
  id: '/(app)/_parents',
  getParentRoute: () => rootRouteImport,
} as any)
const appKidsRoute = appKidsRouteImport.update({
  id: '/(app)/_kids',
  getParentRoute: () => rootRouteImport,
} as any)
const appExamplesRoute = appExamplesRouteImport.update({
  id: '/(app)/_examples',
  getParentRoute: () => rootRouteImport,
} as any)
const appAdminRoute = appAdminRouteImport.update({
  id: '/(app)/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const appExamplesQueryLazyRoute = appExamplesQueryLazyRouteImport
  .update({
    id: '/query',
    path: '/query',
    getParentRoute: () => appExamplesRoute,
  } as any)
  .lazy(() =>
    import('./routes/(app)/_examples/query.lazy').then((d) => d.Route),
  )
const appExamplesFormLazyRoute = appExamplesFormLazyRouteImport
  .update({
    id: '/form',
    path: '/form',
    getParentRoute: () => appExamplesRoute,
  } as any)
  .lazy(() => import('./routes/(app)/_examples/form.lazy').then((d) => d.Route))
const testTestARoute = testTestARouteImport.update({
  id: '/(test)/test/a_',
  path: '/test/a',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthProfileRoute = authAuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => authAuthRoute,
} as any)
const appExamplesUiRoute = appExamplesUiRouteImport.update({
  id: '/ui_',
  path: '/ui',
  getParentRoute: () => appExamplesRoute,
} as any)
const appParentsParentsIndexRoute = appParentsParentsIndexRouteImport.update({
  id: '/parents/',
  path: '/parents/',
  getParentRoute: () => appParentsRoute,
} as any)
const appKidsKidsIndexRoute = appKidsKidsIndexRouteImport.update({
  id: '/kids/',
  path: '/kids/',
  getParentRoute: () => appKidsRoute,
} as any)
const appAdminAdminIndexRoute = appAdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => appAdminRoute,
} as any)
const appExamplesDemoTablesLazyRoute = appExamplesDemoTablesLazyRouteImport
  .update({
    id: '/demo/tables',
    path: '/demo/tables',
    getParentRoute: () => appExamplesRoute,
  } as any)
  .lazy(() =>
    import('./routes/(app)/_examples/demo.tables.lazy').then((d) => d.Route),
  )
const appExamplesDemoDatabaseLazyRoute = appExamplesDemoDatabaseLazyRouteImport
  .update({
    id: '/demo/database',
    path: '/demo/database',
    getParentRoute: () => appExamplesRoute,
  } as any)
  .lazy(() =>
    import('./routes/(app)/_examples/demo.database.lazy').then((d) => d.Route),
  )
const testTestASomethingRoute = testTestASomethingRouteImport.update({
  id: '/(test)/test/a/something',
  path: '/test/a/something',
  getParentRoute: () => rootRouteImport,
} as any)
const testTestABRoute = testTestABRouteImport.update({
  id: '/(test)/test/a/b_',
  path: '/test/a/b',
  getParentRoute: () => rootRouteImport,
} as any)
const appParentsParentsTasksRoute = appParentsParentsTasksRouteImport.update({
  id: '/parents/tasks_',
  path: '/parents/tasks',
  getParentRoute: () => appParentsRoute,
} as any)
const appParentsParentsRewardsRoute =
  appParentsParentsRewardsRouteImport.update({
    id: '/parents/rewards_',
    path: '/parents/rewards',
    getParentRoute: () => appParentsRoute,
  } as any)
const appParentsParentsApprovalsRoute =
  appParentsParentsApprovalsRouteImport.update({
    id: '/parents/approvals',
    path: '/parents/approvals',
    getParentRoute: () => appParentsRoute,
  } as any)
const appParentsParentsAchievementsRoute =
  appParentsParentsAchievementsRouteImport.update({
    id: '/parents/achievements',
    path: '/parents/achievements',
    getParentRoute: () => appParentsRoute,
  } as any)
const appKidsKidsPlayRoute = appKidsKidsPlayRouteImport.update({
  id: '/kids/play',
  path: '/kids/play',
  getParentRoute: () => appKidsRoute,
} as any)
const appKidsKidsHelpRoute = appKidsKidsHelpRouteImport.update({
  id: '/kids/help',
  path: '/kids/help',
  getParentRoute: () => appKidsRoute,
} as any)
const appKidsKidsFitnessRoute = appKidsKidsFitnessRouteImport.update({
  id: '/kids/fitness',
  path: '/kids/fitness',
  getParentRoute: () => appKidsRoute,
} as any)
const appKidsKidsEarnRoute = appKidsKidsEarnRouteImport.update({
  id: '/kids/earn',
  path: '/kids/earn',
  getParentRoute: () => appKidsRoute,
} as any)
const appExamplesUiCategoryRoute = appExamplesUiCategoryRouteImport.update({
  id: '/ui/$category',
  path: '/ui/$category',
  getParentRoute: () => appExamplesRoute,
} as any)
const appAdminAdminUsersRoute = appAdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => appAdminRoute,
} as any)
const appAdminAdminAnalyticsRoute = appAdminAdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => appAdminRoute,
} as any)
const testTestABCRoute = testTestABCRouteImport.update({
  id: '/(test)/test/a/b/c',
  path: '/test/a/b/c',
  getParentRoute: () => rootRouteImport,
} as any)
const appParentsParentsTasksNewRoute =
  appParentsParentsTasksNewRouteImport.update({
    id: '/parents/tasks/new',
    path: '/parents/tasks/new',
    getParentRoute: () => appParentsRoute,
  } as any)
const appParentsParentsTasksSequenceNumberRoute =
  appParentsParentsTasksSequenceNumberRouteImport.update({
    id: '/parents/tasks/$sequenceNumber',
    path: '/parents/tasks/$sequenceNumber',
    getParentRoute: () => appParentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/test': typeof testTestRoute
  '/privacy': typeof appPrivacyLazyRoute
  '/status': typeof appStatusLazyRoute
  '/terms': typeof appTermsLazyRoute
  '/unauthorized': typeof appUnauthorizedLazyRoute
  '/ui': typeof appExamplesUiRoute
  '/profile': typeof authAuthProfileRoute
  '/test/a': typeof testTestARoute
  '/form': typeof appExamplesFormLazyRoute
  '/query': typeof appExamplesQueryLazyRoute
  '/admin/analytics': typeof appAdminAdminAnalyticsRoute
  '/admin/users': typeof appAdminAdminUsersRoute
  '/ui/$category': typeof appExamplesUiCategoryRoute
  '/kids/earn': typeof appKidsKidsEarnRoute
  '/kids/fitness': typeof appKidsKidsFitnessRoute
  '/kids/help': typeof appKidsKidsHelpRoute
  '/kids/play': typeof appKidsKidsPlayRoute
  '/parents/achievements': typeof appParentsParentsAchievementsRoute
  '/parents/approvals': typeof appParentsParentsApprovalsRoute
  '/parents/rewards': typeof appParentsParentsRewardsRoute
  '/parents/tasks': typeof appParentsParentsTasksRoute
  '/test/a/b': typeof testTestABRoute
  '/test/a/something': typeof testTestASomethingRoute
  '/demo/database': typeof appExamplesDemoDatabaseLazyRoute
  '/demo/tables': typeof appExamplesDemoTablesLazyRoute
  '/admin/': typeof appAdminAdminIndexRoute
  '/kids/': typeof appKidsKidsIndexRoute
  '/parents/': typeof appParentsParentsIndexRoute
  '/parents/tasks/$sequenceNumber': typeof appParentsParentsTasksSequenceNumberRoute
  '/parents/tasks/new': typeof appParentsParentsTasksNewRoute
  '/test/a/b/c': typeof testTestABCRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/test': typeof testTestRoute
  '/privacy': typeof appPrivacyLazyRoute
  '/status': typeof appStatusLazyRoute
  '/terms': typeof appTermsLazyRoute
  '/unauthorized': typeof appUnauthorizedLazyRoute
  '/ui': typeof appExamplesUiRoute
  '/profile': typeof authAuthProfileRoute
  '/test/a': typeof testTestARoute
  '/form': typeof appExamplesFormLazyRoute
  '/query': typeof appExamplesQueryLazyRoute
  '/admin/analytics': typeof appAdminAdminAnalyticsRoute
  '/admin/users': typeof appAdminAdminUsersRoute
  '/ui/$category': typeof appExamplesUiCategoryRoute
  '/kids/earn': typeof appKidsKidsEarnRoute
  '/kids/fitness': typeof appKidsKidsFitnessRoute
  '/kids/help': typeof appKidsKidsHelpRoute
  '/kids/play': typeof appKidsKidsPlayRoute
  '/parents/achievements': typeof appParentsParentsAchievementsRoute
  '/parents/approvals': typeof appParentsParentsApprovalsRoute
  '/parents/rewards': typeof appParentsParentsRewardsRoute
  '/parents/tasks': typeof appParentsParentsTasksRoute
  '/test/a/b': typeof testTestABRoute
  '/test/a/something': typeof testTestASomethingRoute
  '/demo/database': typeof appExamplesDemoDatabaseLazyRoute
  '/demo/tables': typeof appExamplesDemoTablesLazyRoute
  '/admin': typeof appAdminAdminIndexRoute
  '/kids': typeof appKidsKidsIndexRoute
  '/parents': typeof appParentsParentsIndexRoute
  '/parents/tasks/$sequenceNumber': typeof appParentsParentsTasksSequenceNumberRoute
  '/parents/tasks/new': typeof appParentsParentsTasksNewRoute
  '/test/a/b/c': typeof testTestABCRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/_admin': typeof appAdminRouteWithChildren
  '/(app)/_examples': typeof appExamplesRouteWithChildren
  '/(app)/_kids': typeof appKidsRouteWithChildren
  '/(app)/_parents': typeof appParentsRouteWithChildren
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(test)/test_': typeof testTestRoute
  '/(app)/privacy': typeof appPrivacyLazyRoute
  '/(app)/status': typeof appStatusLazyRoute
  '/(app)/terms': typeof appTermsLazyRoute
  '/(app)/unauthorized': typeof appUnauthorizedLazyRoute
  '/(app)/_examples/ui_': typeof appExamplesUiRoute
  '/(auth)/_auth/profile': typeof authAuthProfileRoute
  '/(test)/test/a_': typeof testTestARoute
  '/(app)/_examples/form': typeof appExamplesFormLazyRoute
  '/(app)/_examples/query': typeof appExamplesQueryLazyRoute
  '/(app)/_admin/admin/analytics': typeof appAdminAdminAnalyticsRoute
  '/(app)/_admin/admin/users': typeof appAdminAdminUsersRoute
  '/(app)/_examples/ui/$category': typeof appExamplesUiCategoryRoute
  '/(app)/_kids/kids/earn': typeof appKidsKidsEarnRoute
  '/(app)/_kids/kids/fitness': typeof appKidsKidsFitnessRoute
  '/(app)/_kids/kids/help': typeof appKidsKidsHelpRoute
  '/(app)/_kids/kids/play': typeof appKidsKidsPlayRoute
  '/(app)/_parents/parents/achievements': typeof appParentsParentsAchievementsRoute
  '/(app)/_parents/parents/approvals': typeof appParentsParentsApprovalsRoute
  '/(app)/_parents/parents/rewards_': typeof appParentsParentsRewardsRoute
  '/(app)/_parents/parents/tasks_': typeof appParentsParentsTasksRoute
  '/(test)/test/a/b_': typeof testTestABRoute
  '/(test)/test/a/something': typeof testTestASomethingRoute
  '/(app)/_examples/demo/database': typeof appExamplesDemoDatabaseLazyRoute
  '/(app)/_examples/demo/tables': typeof appExamplesDemoTablesLazyRoute
  '/(app)/_admin/admin/': typeof appAdminAdminIndexRoute
  '/(app)/_kids/kids/': typeof appKidsKidsIndexRoute
  '/(app)/_parents/parents/': typeof appParentsParentsIndexRoute
  '/(app)/_parents/parents/tasks/$sequenceNumber': typeof appParentsParentsTasksSequenceNumberRoute
  '/(app)/_parents/parents/tasks/new': typeof appParentsParentsTasksNewRoute
  '/(test)/test/a/b/c': typeof testTestABCRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/test'
    | '/privacy'
    | '/status'
    | '/terms'
    | '/unauthorized'
    | '/ui'
    | '/profile'
    | '/test/a'
    | '/form'
    | '/query'
    | '/admin/analytics'
    | '/admin/users'
    | '/ui/$category'
    | '/kids/earn'
    | '/kids/fitness'
    | '/kids/help'
    | '/kids/play'
    | '/parents/achievements'
    | '/parents/approvals'
    | '/parents/rewards'
    | '/parents/tasks'
    | '/test/a/b'
    | '/test/a/something'
    | '/demo/database'
    | '/demo/tables'
    | '/admin/'
    | '/kids/'
    | '/parents/'
    | '/parents/tasks/$sequenceNumber'
    | '/parents/tasks/new'
    | '/test/a/b/c'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/test'
    | '/privacy'
    | '/status'
    | '/terms'
    | '/unauthorized'
    | '/ui'
    | '/profile'
    | '/test/a'
    | '/form'
    | '/query'
    | '/admin/analytics'
    | '/admin/users'
    | '/ui/$category'
    | '/kids/earn'
    | '/kids/fitness'
    | '/kids/help'
    | '/kids/play'
    | '/parents/achievements'
    | '/parents/approvals'
    | '/parents/rewards'
    | '/parents/tasks'
    | '/test/a/b'
    | '/test/a/something'
    | '/demo/database'
    | '/demo/tables'
    | '/admin'
    | '/kids'
    | '/parents'
    | '/parents/tasks/$sequenceNumber'
    | '/parents/tasks/new'
    | '/test/a/b/c'
  id:
    | '__root__'
    | '/'
    | '/(app)/_admin'
    | '/(app)/_examples'
    | '/(app)/_kids'
    | '/(app)/_parents'
    | '/(auth)/_auth'
    | '/(auth)/login'
    | '/(test)/test_'
    | '/(app)/privacy'
    | '/(app)/status'
    | '/(app)/terms'
    | '/(app)/unauthorized'
    | '/(app)/_examples/ui_'
    | '/(auth)/_auth/profile'
    | '/(test)/test/a_'
    | '/(app)/_examples/form'
    | '/(app)/_examples/query'
    | '/(app)/_admin/admin/analytics'
    | '/(app)/_admin/admin/users'
    | '/(app)/_examples/ui/$category'
    | '/(app)/_kids/kids/earn'
    | '/(app)/_kids/kids/fitness'
    | '/(app)/_kids/kids/help'
    | '/(app)/_kids/kids/play'
    | '/(app)/_parents/parents/achievements'
    | '/(app)/_parents/parents/approvals'
    | '/(app)/_parents/parents/rewards_'
    | '/(app)/_parents/parents/tasks_'
    | '/(test)/test/a/b_'
    | '/(test)/test/a/something'
    | '/(app)/_examples/demo/database'
    | '/(app)/_examples/demo/tables'
    | '/(app)/_admin/admin/'
    | '/(app)/_kids/kids/'
    | '/(app)/_parents/parents/'
    | '/(app)/_parents/parents/tasks/$sequenceNumber'
    | '/(app)/_parents/parents/tasks/new'
    | '/(test)/test/a/b/c'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appAdminRoute: typeof appAdminRouteWithChildren
  appExamplesRoute: typeof appExamplesRouteWithChildren
  appKidsRoute: typeof appKidsRouteWithChildren
  appParentsRoute: typeof appParentsRouteWithChildren
  authAuthRoute: typeof authAuthRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  testTestRoute: typeof testTestRoute
  appPrivacyLazyRoute: typeof appPrivacyLazyRoute
  appStatusLazyRoute: typeof appStatusLazyRoute
  appTermsLazyRoute: typeof appTermsLazyRoute
  appUnauthorizedLazyRoute: typeof appUnauthorizedLazyRoute
  testTestARoute: typeof testTestARoute
  testTestABRoute: typeof testTestABRoute
  testTestASomethingRoute: typeof testTestASomethingRoute
  testTestABCRoute: typeof testTestABCRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/unauthorized': {
      id: '/(app)/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof appUnauthorizedLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/terms': {
      id: '/(app)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof appTermsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/status': {
      id: '/(app)/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof appStatusLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/privacy': {
      id: '/(app)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof appPrivacyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(test)/test_': {
      id: '/(test)/test_'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof testTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_parents': {
      id: '/(app)/_parents'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_kids': {
      id: '/(app)/_kids'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appKidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_examples': {
      id: '/(app)/_examples'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_admin': {
      id: '/(app)/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_examples/query': {
      id: '/(app)/_examples/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof appExamplesQueryLazyRouteImport
      parentRoute: typeof appExamplesRoute
    }
    '/(app)/_examples/form': {
      id: '/(app)/_examples/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof appExamplesFormLazyRouteImport
      parentRoute: typeof appExamplesRoute
    }
    '/(test)/test/a_': {
      id: '/(test)/test/a_'
      path: '/test/a'
      fullPath: '/test/a'
      preLoaderRoute: typeof testTestARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth/profile': {
      id: '/(auth)/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof authAuthProfileRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(app)/_examples/ui_': {
      id: '/(app)/_examples/ui_'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof appExamplesUiRouteImport
      parentRoute: typeof appExamplesRoute
    }
    '/(app)/_parents/parents/': {
      id: '/(app)/_parents/parents/'
      path: '/parents'
      fullPath: '/parents/'
      preLoaderRoute: typeof appParentsParentsIndexRouteImport
      parentRoute: typeof appParentsRoute
    }
    '/(app)/_kids/kids/': {
      id: '/(app)/_kids/kids/'
      path: '/kids'
      fullPath: '/kids/'
      preLoaderRoute: typeof appKidsKidsIndexRouteImport
      parentRoute: typeof appKidsRoute
    }
    '/(app)/_admin/admin/': {
      id: '/(app)/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof appAdminAdminIndexRouteImport
      parentRoute: typeof appAdminRoute
    }
    '/(app)/_examples/demo/tables': {
      id: '/(app)/_examples/demo/tables'
      path: '/demo/tables'
      fullPath: '/demo/tables'
      preLoaderRoute: typeof appExamplesDemoTablesLazyRouteImport
      parentRoute: typeof appExamplesRoute
    }
    '/(app)/_examples/demo/database': {
      id: '/(app)/_examples/demo/database'
      path: '/demo/database'
      fullPath: '/demo/database'
      preLoaderRoute: typeof appExamplesDemoDatabaseLazyRouteImport
      parentRoute: typeof appExamplesRoute
    }
    '/(test)/test/a/something': {
      id: '/(test)/test/a/something'
      path: '/test/a/something'
      fullPath: '/test/a/something'
      preLoaderRoute: typeof testTestASomethingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(test)/test/a/b_': {
      id: '/(test)/test/a/b_'
      path: '/test/a/b'
      fullPath: '/test/a/b'
      preLoaderRoute: typeof testTestABRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_parents/parents/tasks_': {
      id: '/(app)/_parents/parents/tasks_'
      path: '/parents/tasks'
      fullPath: '/parents/tasks'
      preLoaderRoute: typeof appParentsParentsTasksRouteImport
      parentRoute: typeof appParentsRoute
    }
    '/(app)/_parents/parents/rewards_': {
      id: '/(app)/_parents/parents/rewards_'
      path: '/parents/rewards'
      fullPath: '/parents/rewards'
      preLoaderRoute: typeof appParentsParentsRewardsRouteImport
      parentRoute: typeof appParentsRoute
    }
    '/(app)/_parents/parents/approvals': {
      id: '/(app)/_parents/parents/approvals'
      path: '/parents/approvals'
      fullPath: '/parents/approvals'
      preLoaderRoute: typeof appParentsParentsApprovalsRouteImport
      parentRoute: typeof appParentsRoute
    }
    '/(app)/_parents/parents/achievements': {
      id: '/(app)/_parents/parents/achievements'
      path: '/parents/achievements'
      fullPath: '/parents/achievements'
      preLoaderRoute: typeof appParentsParentsAchievementsRouteImport
      parentRoute: typeof appParentsRoute
    }
    '/(app)/_kids/kids/play': {
      id: '/(app)/_kids/kids/play'
      path: '/kids/play'
      fullPath: '/kids/play'
      preLoaderRoute: typeof appKidsKidsPlayRouteImport
      parentRoute: typeof appKidsRoute
    }
    '/(app)/_kids/kids/help': {
      id: '/(app)/_kids/kids/help'
      path: '/kids/help'
      fullPath: '/kids/help'
      preLoaderRoute: typeof appKidsKidsHelpRouteImport
      parentRoute: typeof appKidsRoute
    }
    '/(app)/_kids/kids/fitness': {
      id: '/(app)/_kids/kids/fitness'
      path: '/kids/fitness'
      fullPath: '/kids/fitness'
      preLoaderRoute: typeof appKidsKidsFitnessRouteImport
      parentRoute: typeof appKidsRoute
    }
    '/(app)/_kids/kids/earn': {
      id: '/(app)/_kids/kids/earn'
      path: '/kids/earn'
      fullPath: '/kids/earn'
      preLoaderRoute: typeof appKidsKidsEarnRouteImport
      parentRoute: typeof appKidsRoute
    }
    '/(app)/_examples/ui/$category': {
      id: '/(app)/_examples/ui/$category'
      path: '/ui/$category'
      fullPath: '/ui/$category'
      preLoaderRoute: typeof appExamplesUiCategoryRouteImport
      parentRoute: typeof appExamplesRoute
    }
    '/(app)/_admin/admin/users': {
      id: '/(app)/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof appAdminAdminUsersRouteImport
      parentRoute: typeof appAdminRoute
    }
    '/(app)/_admin/admin/analytics': {
      id: '/(app)/_admin/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof appAdminAdminAnalyticsRouteImport
      parentRoute: typeof appAdminRoute
    }
    '/(test)/test/a/b/c': {
      id: '/(test)/test/a/b/c'
      path: '/test/a/b/c'
      fullPath: '/test/a/b/c'
      preLoaderRoute: typeof testTestABCRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_parents/parents/tasks/new': {
      id: '/(app)/_parents/parents/tasks/new'
      path: '/parents/tasks/new'
      fullPath: '/parents/tasks/new'
      preLoaderRoute: typeof appParentsParentsTasksNewRouteImport
      parentRoute: typeof appParentsRoute
    }
    '/(app)/_parents/parents/tasks/$sequenceNumber': {
      id: '/(app)/_parents/parents/tasks/$sequenceNumber'
      path: '/parents/tasks/$sequenceNumber'
      fullPath: '/parents/tasks/$sequenceNumber'
      preLoaderRoute: typeof appParentsParentsTasksSequenceNumberRouteImport
      parentRoute: typeof appParentsRoute
    }
  }
}

interface appAdminRouteChildren {
  appAdminAdminAnalyticsRoute: typeof appAdminAdminAnalyticsRoute
  appAdminAdminUsersRoute: typeof appAdminAdminUsersRoute
  appAdminAdminIndexRoute: typeof appAdminAdminIndexRoute
}

const appAdminRouteChildren: appAdminRouteChildren = {
  appAdminAdminAnalyticsRoute: appAdminAdminAnalyticsRoute,
  appAdminAdminUsersRoute: appAdminAdminUsersRoute,
  appAdminAdminIndexRoute: appAdminAdminIndexRoute,
}

const appAdminRouteWithChildren = appAdminRoute._addFileChildren(
  appAdminRouteChildren,
)

interface appExamplesRouteChildren {
  appExamplesUiRoute: typeof appExamplesUiRoute
  appExamplesFormLazyRoute: typeof appExamplesFormLazyRoute
  appExamplesQueryLazyRoute: typeof appExamplesQueryLazyRoute
  appExamplesUiCategoryRoute: typeof appExamplesUiCategoryRoute
  appExamplesDemoDatabaseLazyRoute: typeof appExamplesDemoDatabaseLazyRoute
  appExamplesDemoTablesLazyRoute: typeof appExamplesDemoTablesLazyRoute
}

const appExamplesRouteChildren: appExamplesRouteChildren = {
  appExamplesUiRoute: appExamplesUiRoute,
  appExamplesFormLazyRoute: appExamplesFormLazyRoute,
  appExamplesQueryLazyRoute: appExamplesQueryLazyRoute,
  appExamplesUiCategoryRoute: appExamplesUiCategoryRoute,
  appExamplesDemoDatabaseLazyRoute: appExamplesDemoDatabaseLazyRoute,
  appExamplesDemoTablesLazyRoute: appExamplesDemoTablesLazyRoute,
}

const appExamplesRouteWithChildren = appExamplesRoute._addFileChildren(
  appExamplesRouteChildren,
)

interface appKidsRouteChildren {
  appKidsKidsEarnRoute: typeof appKidsKidsEarnRoute
  appKidsKidsFitnessRoute: typeof appKidsKidsFitnessRoute
  appKidsKidsHelpRoute: typeof appKidsKidsHelpRoute
  appKidsKidsPlayRoute: typeof appKidsKidsPlayRoute
  appKidsKidsIndexRoute: typeof appKidsKidsIndexRoute
}

const appKidsRouteChildren: appKidsRouteChildren = {
  appKidsKidsEarnRoute: appKidsKidsEarnRoute,
  appKidsKidsFitnessRoute: appKidsKidsFitnessRoute,
  appKidsKidsHelpRoute: appKidsKidsHelpRoute,
  appKidsKidsPlayRoute: appKidsKidsPlayRoute,
  appKidsKidsIndexRoute: appKidsKidsIndexRoute,
}

const appKidsRouteWithChildren =
  appKidsRoute._addFileChildren(appKidsRouteChildren)

interface appParentsRouteChildren {
  appParentsParentsAchievementsRoute: typeof appParentsParentsAchievementsRoute
  appParentsParentsApprovalsRoute: typeof appParentsParentsApprovalsRoute
  appParentsParentsRewardsRoute: typeof appParentsParentsRewardsRoute
  appParentsParentsTasksRoute: typeof appParentsParentsTasksRoute
  appParentsParentsIndexRoute: typeof appParentsParentsIndexRoute
  appParentsParentsTasksSequenceNumberRoute: typeof appParentsParentsTasksSequenceNumberRoute
  appParentsParentsTasksNewRoute: typeof appParentsParentsTasksNewRoute
}

const appParentsRouteChildren: appParentsRouteChildren = {
  appParentsParentsAchievementsRoute: appParentsParentsAchievementsRoute,
  appParentsParentsApprovalsRoute: appParentsParentsApprovalsRoute,
  appParentsParentsRewardsRoute: appParentsParentsRewardsRoute,
  appParentsParentsTasksRoute: appParentsParentsTasksRoute,
  appParentsParentsIndexRoute: appParentsParentsIndexRoute,
  appParentsParentsTasksSequenceNumberRoute:
    appParentsParentsTasksSequenceNumberRoute,
  appParentsParentsTasksNewRoute: appParentsParentsTasksNewRoute,
}

const appParentsRouteWithChildren = appParentsRoute._addFileChildren(
  appParentsRouteChildren,
)

interface authAuthRouteChildren {
  authAuthProfileRoute: typeof authAuthProfileRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthProfileRoute: authAuthProfileRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appAdminRoute: appAdminRouteWithChildren,
  appExamplesRoute: appExamplesRouteWithChildren,
  appKidsRoute: appKidsRouteWithChildren,
  appParentsRoute: appParentsRouteWithChildren,
  authAuthRoute: authAuthRouteWithChildren,
  authLoginRoute: authLoginRoute,
  testTestRoute: testTestRoute,
  appPrivacyLazyRoute: appPrivacyLazyRoute,
  appStatusLazyRoute: appStatusLazyRoute,
  appTermsLazyRoute: appTermsLazyRoute,
  appUnauthorizedLazyRoute: appUnauthorizedLazyRoute,
  testTestARoute: testTestARoute,
  testTestABRoute: testTestABRoute,
  testTestASomethingRoute: testTestASomethingRoute,
  testTestABCRoute: testTestABCRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
